; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; common settings for all environments
[env]
platform = espressif32 @ ^7.0.1
framework = arduino

; If ESPTool fails to read or write all of the firmware, reduce the baud rate of the connection (e.g., to 115200 or less).
upload_speed = 921600
monitor_speed = 115200

; ignore library versions from PIO registry, using custom modified versions in /lib folder instead.
; This is just for reference the modified libraries used in the project!
; Do not uncomment the lines below!
; lib_ignore =
;   bodmer/TFT_eSPI  ; ignore PIO registry version of TFT_eSPI, using custom modified version in /lib
;   arduino-libraries/NTPClient ; ignore PIO registry version, using custom modified version in /lib
;   sparkfun/SparkFun APDS9960 RGB and Gesture Sensor ; ignore PIO registry version, using custom modified version in /lib

; Tested and working with following versions. If you have issues, revert to library versions listed below.
lib_deps =
  adafruit/Adafruit NeoPixel ; adafruit/Adafruit NeoPixel@1.15.5
  paulstoffregen/Time ; paulstoffregen/Time@1.6.1
  ; bodmer/TFT_eSPI ; bodmer/TFT_eSPI@2.5.43  -- DISABLED: using local modified version (see below)
  knolleary/PubSubClient ; knolleary/PubSubClient@2.8.0
  bblanchon/ArduinoJson ; bblanchon/ArduinoJson@7.4.3
  makuna/RTC ; makuna/RTC@2.5.0
  adafruit/RTClib ; adafruit/RTClib@^2.1.4

  ; The following libraries are compiled directly from the local /lib folder with custom modifications
  ; They are not copied to the .pio/libdeps folder! Except you uncomment the line below. This is NOT needed and NOT recommended!
  ; This is just for reference the modified libraries used in the project!
  ; Do not uncomment the lines below!
  ; file://./lib/modified_TFT_eSPI ; local copy of bodmer/TFT_eSPI@2.5.43 library with custom modifications for ESP32-C3 support and other fixes
  ; file://./lib/modified_NTPClient ; local copy of arduino-libraries/NTPClient@3.2.1 library with custom modifications
  ; file://./lib/modified_SparkFun APDS9960 RGB and Gesture Sensor ; local copy of sparkfun/SparkFun APDS9960 RGB and Gesture Sensor@1.0.7 library with custom modifications
  ; file://./lib/modified_RTC_RX8025T ; local copy of https://github.com/marcinsaj/RTC_RX8025T library with custom modifications

build_flags =
  -D BUILDVER=1.3.13 ; Set to current version of the firmware
  -D CORE_DEBUG_LEVEL=0 ; Set to 0 for no debug (saves flash memory); Set to 5 for full debug
  -D CREATE_FIRMWAREFILE ; Set to generate filesystem image and combined binary

board_build.filesystem = littlefs

extra_scripts =
  pre:scripts/script_rename_firmware.py ; PlatformIO custom firmware/program name
  pre:scripts/script_configure_tft_lib.py ; Copy configuration files into TFT_eSPI library folder
  post:scripts/script_build_unified_binary.py ; Build unified firmware that can be flashed from 0x0 in one go

; https://github.com/danmar/cppcheck/blob/main/man/manual.md
check_flags =
    --enable=all
    --suppress=unusedFunction
    ; --suppressions-list=<file>

; PIO environment for original EleksTube IPS clocks with 4MB flash.
[env:EleksTube]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D HARDWARE_ELEKSTUBE_CLOCK
board_build.partitions = partition_4MB.csv

; PIO environment for original EleksTube clock Gen2.1 (EleksTube IPS Classic Edition/Pro/PR1/PR2, ESP32 Pico D4 Chip).
[env:EleksTube_Gen2]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D HARDWARE_ELEKSTUBE_GEN2_CLOCK
board_build.partitions = partition_4MB.csv

; PIO environment for the Si Hai copy of the clock.
[env:SI_HAI]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D HARDWARE_SI_HAI_CLOCK
board_build.partitions = partition_4MB.csv

; PIO environment for the Xunfeng copy of the clock (with ESP32-S2 Wroom).
[env:Xunfeng]
board = esp32devs2xunfeng
build_flags =
  ${env.build_flags}
  -D HARDWARE_XUNFENG_CLOCK
board_build.partitions = partition_4MB.csv

; PIO environment for the NovelLife clocks.
;   NovelLife SE version (Gesture only) - tested and working!
;   Non-SE version (Buttons only) NOT tested!
;   Pro version (Buttons and Gesture) NOT tested!
[env:NovelLife]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D HARDWARE_NOVELLIFE_CLOCK
board_build.partitions = partition_4MB.csv

; PIO environment for the PunkCyber / RGB Glow tube / PCBway clocks.
[env:PunkCyber]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D HARDWARE_PUNKCYBER_CLOCK
board_build.partitions = partition_4MB.csv

; PIO environment for all clocks with 8MB flash on PCB (like the IPSTube model H401 and H402).
[env:IPSTube]
board = esp32devipstube
build_flags =
  ${env.build_flags}
  -D HARDWARE_IPSTUBE_CLOCK
  ; -D HARDWAREMOD_IPSTUBE_CLOCK_WITH_LED_STRIPE
  ; -D HARDWAREMOD_IPSTUBE_CLOCK_WITHOUT_DIMMING_TRANSISTOR
board_build.partitions = partition_8MB.csv

; PIO environment for the MarvelTubes clock (with ESP32-S2).
[env:MarvelTubes]
board = esp32devs2marveltubes
build_flags =
  ${env.build_flags}
  -D HARDWARE_MARVELTUBES_CLOCK
board_build.partitions = partition_16MB.csv

; PIO environment for the MarvelTubes Gen2 clock (with ESP32, 16MB flash).
[env:MarvelTubes_Gen2]
board = esp32devmarveltubesgen2
build_flags =
  ${env.build_flags}
  -D HARDWARE_MARVELTUBES_GEN2_CLOCK
board_build.partitions = partition_16MB.csv

; PIO environment for the MarvelTubes Mini clock (ESP32-C3 Mini 1).
[env:MarvelTubesMini]
board = esp32devc3minimarveltubesmini
; extra scripts needed again, because one more script is added to prepare mini clockfaces (convert them to 80x160 resolution and set an alternative data folder)
; and the block is overridden, so we need to redefine the whole block here.
extra_scripts =
  pre:scripts/script_prepare_mini_clockfaces.py ; Prepare mini clockfaces by converting them to 80x160 resolution and setting an alternative data folder
  pre:scripts/script_rename_firmware.py ; PlatformIO custom firmware/program name
  pre:scripts/script_configure_tft_lib.py ; Copy configuration files into TFT_eSPI library folder
  post:scripts/script_build_unified_binary.py ; Build unified firmware that can be flashed from 0x0 in one go
build_flags =
  ${env.build_flags}
  -D HARDWARE_MARVELTUBESMINI_CLOCK
board_build.partitions = partition_4MB.csv

; The MarvelTubes Mini clock has a different USB-serial chip that supports USB-CDC, if DTS and RTS signals are not disabled, the clock will either not boot properly
; after flashing or will stop working after a serial monitoring session.
; However, the DTR and RTS signals should be DISABLED for monitoring.
monitor_dtr = 0
monitor_rts = 0

; PIO environment for the D-Esign clock (ESP32 WROOM-32, small ST7735 80x160 displays, direct GPIO CS lines).
[env:DEsign]
board = esp32dev
; extra scripts needed again, because one more script is added to prepare mini clockfaces (convert them to 80x160 resolution and set an alternative data folder)
; and the block is overridden, so we need to redefine the whole block here.
extra_scripts =
  pre:scripts/script_prepare_mini_clockfaces.py ; Prepare mini clockfaces by converting them to 80x160 resolution and setting an alternative data folder
  pre:scripts/script_rename_firmware.py ; PlatformIO custom firmware/program name
  pre:scripts/script_configure_tft_lib.py ; Copy configuration files into TFT_eSPI library folder
  post:scripts/script_build_unified_binary.py ; Build unified firmware that can be flashed from 0x0 in one go
build_flags =
  ${env.build_flags}
  -D HARDWARE_DESIGN_CLOCK
board_build.partitions = partition_4MB.csv
